### ISSUE TITLE
HEVC (H.265) videos cannot be played in some browsers

### ISSUE THREAD

**Issue by PJM257** [404talentnotfound/Glomble#2] opened 2024-10-12 02:34 UTC
The HEVC or H.265 codec used on most Glomble videos is not supported by some browsers due to patent reasons, such as Firefox. There should be a system to detect and either prohibit or convert uploads using the H.265 codec. Most other codecs should be fine, and VP9 (AV1) using the .webm container offers a better compression ratio and much wider browser compatibility compared to H.265 and is overall a better codec for web videos.

**Comment by 404talentnotfound** [comment] 2024-10-12 09:55
I see, thank you. I will implement this as soon as possible. There's a big
update on the way so this might take a day or two

**Comment by 404talentnotfound** [comment] 2024-10-12 20:47
fixed with the new update, thanks for letting me know the root cause!

**Closed** 2024-10-12 20:46 UTC
